apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: kc
type: Opaque
stringData:
  POSTGRESQL_DATABASE: keycloak
  POSTGRESQL_USER: keycloak
  POSTGRESQL_PASSWORD: redhat
  username: keycloak
  password: redhat
