apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhbk
  namespace: kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres
    port: 5432
    database: keycloak
    usernameSecret:
      name: pg-secret
      key: username
    passwordSecret:
      name: pg-secret
      key: password
  http:
    httpEnabled: true
  ingress:
    enabled: true
    className: openshift-default
  hostname:
    strict: true
    strict-https: true
  proxy:
    headers: xforwarded 
  features:
    enabled:
      - authorization
  additionalOptions:
    - name: proxy
      value: edge
