apiVersion: v1
kind: Secret
metadata:
  name: system-database
  namespace: poc
type: Opaque
stringData:
  URL: "postgresql://user:password@<AURORA_PG_ENDPOINT>:5432/system_production?sslmode=require"
---
apiVersion: v1
kind: Secret
metadata:
  name: zync
  namespace: poc
type: Opaque
stringData:
  DATABASE_URL: "postgresql://user:password@<AURORA_PG_ENDPOINT>:5432/zync_production?sslmode=require"
  ZYNC_DATABASE_PASSWORD: "redhat"
