apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: threescale-og
  namespace: 3scale
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: threescale-operator
  namespace: 3scale
spec:
  channel: stable
  name: threescale-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
